### ISSUE TITLE
The processing time for the step2 of Demo

### ISSUE THREAD

**Issue by Samuelcdf** [mhorlbeck/ScreenProcessing#20] opened 2022-10-20 01:09 UTC
The time spent is far different than which said in the pdf file. The time mentioned in the pdf is about 5 minutes, but I spent more than one day.

May I have your help to figure out the possible problem?

The script was run under python 3.10 with numpy, scipy, pandas and matlotlib packages installed.

**Comment by mhorlbeck** [comment] 2023-02-03 23:26
I am guessing this is a duplicate of #21 caused by a change in the scipy mann-whitney function. still slower than before, but should complete in a reasonable time. will work on parallelizing the mw step to speed things up futher.

**Closed as completed by mhorlbeck** 2023-02-03 23:26 UTC
